#ifndef BOARD_CONFIG_H
#define BOARD_CONFIG_H

#define VENDOR_NAME "EXDS"
#define PRODUCT_NAME "STW-SIM"
#define VOLUME_LABEL "STWBOOT"
#define BOARD_ID "SAMDV70N19B-SIM_STW"

#define USB_VID 0x239A
#define USB_PID 0x0013

#define LED_PIN PIN_PA17
#define LED_TX_PIN PIN_PA27
#define LED_RX_PIN PIN_PA31

#define BOARD_NEOPIXEL_PIN PIN_PA30
#define BOARD_NEOPIXEL_COUNT 1

#endif
